"""
Milestone 3 - Response Formatter

Formats the final AI response together with
Knowledge Base metadata.

Supports multiple retrieved documents and
provides clean metadata for the backend.
"""

import logging
from typing import Any

logger = logging.getLogger(__name__)


def format_response(
    llm_response: str,
    retrieved_docs: list[dict[str, Any]] | None,
) -> dict[str, Any]:
    """
    Format the final AI response together with
    Knowledge Base metadata.

    Parameters
    ----------
    llm_response : str
        Response generated by the LLM.

    retrieved_docs : list[dict] | None
        Retrieved Knowledge Base documents.

    Returns
    -------
    dict
        Formatted response ready for the backend.
    """

    logger.info("Formatting AI response.")

    # ---------------------------------------------------
    # No retrieved documents
    # ---------------------------------------------------

    if not retrieved_docs:
        logger.warning("No source documents available.")

        return {
            "resolution": llm_response.strip(),
            "sources": [],
            "documents_used": 0,
            "retrieval_distance": None,
        }

    # ---------------------------------------------------
    # Build Source List
    # ---------------------------------------------------

    sources = []

    distances = []

    for doc in retrieved_docs:

        distance = doc.get("retrieval_distance")

        try:
            distance = (
                round(float(distance), 3)
                if distance is not None
                else None
            )

        except (TypeError, ValueError):

            logger.warning(
                "Invalid retrieval distance for KB %s",
                doc.get("kb_id", "Unknown"),
            )

            distance = None

        if distance is not None:
            distances.append(distance)

        sources.append(
            {
                "kb_id": doc.get("kb_id"),
                "title": doc.get("title"),
                "category": doc.get("category"),
                "tags": doc.get("tags"),
                "retrieval_distance": distance,
            }
        )

    # ---------------------------------------------------
    # Best Retrieval Distance
    # ---------------------------------------------------

    best_distance = (
        min(distances)
        if distances
        else None
    )

    logger.info(
        "Formatted response using %d KB document(s).",
        len(sources),
    )

    # ---------------------------------------------------
    # Final Response
    # ---------------------------------------------------

    return {
        "resolution": llm_response.strip(),
        "sources": sources,
        "documents_used": len(sources),
        "retrieval_distance": best_distance,
    }